server:
  port: 8761

spring:
  application:
    name: eureka-server
    title: eureka-server
    version: v1.0

eureka:
  instance:
    hostname: localhost
    upper-case-service-id: false # Prevents Eureka from converting service IDs to uppercase
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
